### ISSUE TITLE
only facebook, twitter and linkedin?

### ISSUE THREAD

**Issue by HectorRPL** [thisissoon/angular-post#1]
what?.... and the other social? only three (facebook, twitter and linkedin)?

**Comment by edoparearyee** [comment]
Hi @HectorRPL this library works with all social platforms that Po.st supports, these three are just an example.

See full config options here: https://post.zendesk.com/hc/en-us/articles/208458026-v4-Global-Configuration-window-pwidget-config- 

Or simply configure the widgets through your Po.st account here: https://www.po.st/portal/button/ and copy the config

an example config with some other social media accounts: 

```j
{
    "buttons": [{
        "id": "pinterest"
    }, {
        "id": "googleplus"
    }, {
        "id": "tumblr"
    }],
    "buttonColor": "default",
    "buttonBackground": "default",
    "label": false,
    "radius": "square",
    "size": "32",
    "counter": false,
    "layout": "horizontal",
    "jumbo": false,
    "padding": false,
    "view": "auto",
    "shareNewWindow": true,
    "services": {
        "twitter": {
            "via": "po_st"
        }
    },
    "rules": {
        "clearUrlParameters": true
    }
}
```
